### ISSUE TITLE
[BUG] Local development with UDP intergration

### ISSUE THREAD

**Issue by noinarisak** [udplabs/zartan#145]
**Describe the bug**
When executing local development with the following command and going to `http:/localhost:8080` on chrome I get an error.

**To Reproduce**
1. On cli `$ python app.py`
2. Launch Chrome and navigate to `http:/localhost:8080`

**Expected behavior**
The application should load up.

**Screenshots**

```bash
2020-05-14 09:25:27,535 - utils.udp - DEBUG - apply_remote_config()
2020-05-14 09:25:27,536 - utils.udp - DEBUG - is_configured_remotley()
2020-05-14 09:25:27,536 - utils.udp - INFO - Domain is not confgured.  pulling configuration from UDP
2020-05-14 09:25:27,536 - utils.udp - DEBUG - get_domain_parts_from_request()
Traceback (most recent call last):
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/xdata/_prj/zartan/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/xdata/_prj/zartan/utils/udp.py", line 39, in decorated_function
    domain_parts = get_domain_parts_from_request()
  File "/xdata/_prj/zartan/utils/udp.py", line 148, in get_domain_parts_from_request
    udp_app_name = domain_parts[1]
IndexError: list index out of range
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: latest

**Additional context**

**Comment by noinarisak** [comment]
Is not an issue due to the recent release v1.
